name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file dockerfile --tag ghcr.io/npenin/httpholepunch
      - name: publish the docker image
        run: docker push ghcr.io/npenin/httpholepunch
